/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exemplos.uri1002;

import org.junit.Test;
import static org.junit.Assert.*;

public class CirculoTest {
    @Test public void testSomeLibraryMethod() {
        Circulo classUnderTest = new Circulo();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
