/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exemplos.uri1002;

/**
 * 
 * @author marco
 *
 */
public class Circulo {
	
	/*
	 * 
	 */
	private double raio;

	/*
	 * 
	 */
	private static final double PI = 3.14159;

	/**
	 * @param raio
	 */
	public Circulo(double raio) {
		super();
		this.raio = raio;
	}

	/**
	 * @return the area
	 */
	public double getArea() {
		return raio * raio * PI;
	}

}
